spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flawadb
    username: root
    password: flawa
  output: 
    ansi.enabled: ALWAYS
app:
  bitcoin:
    network: Regtest
logging:
    file: logs/myapp.log
    level:
        org.springframework.web: INFO
        jp.co.simplex.fwallet: DEBUG